spring.application.name=prova
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/treino1_prova
spring.datasource.username=postgres
spring.datasource.password=post